- name: Install git and other developer tools
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: no
  with_items:
    - geany   # lightweight but reasonably potent text editor
    - git
    - gitk
    - openssh-client
    - terminator  # multi-pane terminal emulator
    - xpdf   # lightweight pdf viewer
  sudo: yes

- name: Copy bash configuration
  copy:
    src: ../files/bashrc.sh
    dest: /home/vagrant/.bashrc

- name: Copy git configuration
  copy:
    src: ../files/git-config
    dest: /home/vagrant/.gitconfig

- name: Ensure required directories exist
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /home/vagrant/.config/terminator
    - /home/vagrant/Desktop

- name: Copy terminator configuration
  copy:
    src: ../files/terminator-config
    dest: /home/vagrant/.config/terminator/config

- name: Create shortcuts on desktop
  copy:
    src: ../files/Terminal.desktop
    dest: /home/vagrant/Desktop/Terminal.desktop
