- name: Install git and other developer tools
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: no
  with_items:
    - geany   # lightweight but reasonably potent text editor
    - git
    - gitk
    - openssh-client
    - terminator  # multi-pane terminal emulator
    - xpdf   # lightweight pdf viewer
  sudo: yes

- name: Copy bash configuration
  copy:
    src: ../files/bashrc.sh
    dest: /home/vagrant/.bashrc

- name: Copy git configuration
  copy:
    src: ../files/git-config
    dest: /home/vagrant/.gitconfig

- name: Ensure required directories exist
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /home/vagrant/.config/terminator
    - /home/vagrant/Desktop
    - /home/vagrant/.config/pcmanfm/LXDE
    - /home/vagrant/.local/share/applications

- name: Copy terminator configuration
  copy:
    src: ../files/terminator-config
    dest: /home/vagrant/.config/terminator/config

- name: Create shortcuts on desktop
  copy:
    src: ../files/Terminal.desktop
    dest: /home/vagrant/Desktop/Terminal.desktop

- name: Set default applications for certain filetypes
  copy:
    src: ../files/mimeapps.list
    dest: /home/vagrant/.local/share/applications/mimeapps.list

- name: Download a Lily Pond wallpaper
  get_url:
    url: http://upload.wikimedia.org/wikipedia/commons/a/a7/Lily_Pond_%287396038174%29.jpg
    dest: /home/vagrant/.lily-wallpaper

- name: Set the wallpaper
  copy:
    content: |
      [*]
      wallpaper=/home/vagrant/.lily-wallpaper
      wallpaper_mode=fit
      wallpaper_common=1
    dest: /home/vagrant/.config/pcmanfm/LXDE/desktop-items-0.conf
