# We must start with apt-get update - the information about apt packages saved
# in the base box is usually outdated (and would cause apt-get install to fail).

- name: Update APT package metadata
  apt:
    update_cache: yes
    cache_valid_time: 3600
  sudo: yes
